version: '3.8'
services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    depends_on:
      - mongo
    environment:
      MONGODB_URI: "mongodb://mongo:27017/pvabazaar"
      PORT: "5001"
      NODE_ENV: "development"
      DEV_AUTO_SEED: "true"
      JWT_SECRET: "dev_jwt_secret"
      ADMIN_SECRET_CODE: "dev_admin_code"
      USE_MEMORY_DB: "false"
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
    command: sh -c "sleep 5 && node seed.js || true && node api/index.js"

  frontend:
    build: ./Frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    environment:
      VITE_API_URL: "http://localhost:5001"

volumes:
  mongo-data:
