services:
  - type: web
    name: pva-bazaar-api-prod
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: JWT_SECRET
        value: pva_jwt_secret_key_change_this_to_something_longer_32_chars_minimum
      - key: MONGODB_URI
        value: mongodb+srv://pva_admin:pva_bazaar_2024@pvabazaar.mongodb.net/pvabazaar?retryWrites=true&w=majority
      - key: ETHEREUM_RPC_URL
        value: https://polygon-amoy-rpc.publicnode.com
