#!/usr/bin/env bash
# Production Configuration Helper
# This script helps you manually add environment variables to Vercel

echo "======================================"
echo "   PVA Bazaar Production Setup"
echo "======================================"
echo ""

# Color codes
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}Generated Production Secrets:${NC}"
echo ""
echo "NEXTAUTH_SECRET="
echo "yIklmeTFv8pLDoY6Qu7SEbRzK5nBCgqJZjXtW2cUdr3MGs4OxHPw1Af0haN9"
echo ""
echo "DID_SEED="
echo "2668c0dee48b9810fda17ec69c95f489a5c031fa15e650dc7fda528c5ff5c646"
echo ""
echo -e "${YELLOW}Deployment URLs:${NC}"
echo ""
echo "Backend:    https://pva-backend-h6zkzdmjy-pvagrs-projects.vercel.app"
echo "Livestream: https://pvabazaar-livestream-o3okjf15o-pvagrs-projects.vercel.app"
echo "Frontend:   https://pvabazaar.org"
echo ""

echo -e "${GREEN}STEPS TO COMPLETE SETUP:${NC}"
echo ""
echo "1. Go to Vercel Dashboard:"
echo "   https://vercel.com/pvagrs-projects/pvabazaar-livestream/settings/environment-variables"
echo ""
echo "2. Click 'Add New' and add these variables:"
echo ""
echo "   Variable Name: NEXTAUTH_URL"
echo "   Value: https://pvabazaar-livestream-o3okjf15o-pvagrs-projects.vercel.app"
echo "   Environments: Production, Preview, Development"
echo ""
echo "   Variable Name: NEXTAUTH_SECRET"
echo "   Value: yIklmeTFv8pLDoY6Qu7SEbRzK5nBCgqJZjXtW2cUdr3MGs4OxHPw1Af0haN9"
echo "   Environments: Production, Preview, Development"
echo ""
echo "   Variable Name: NEXT_PUBLIC_API_URL"
echo "   Value: https://pva-backend-h6zkzdmjy-pvagrs-projects.vercel.app"
echo "   Environments: Production, Preview, Development"
echo ""
echo "   Variable Name: DID_SEED"
echo "   Value: 2668c0dee48b9810fda17ec69c95f489a5c031fa15e650dc7fda528c5ff5c646"
echo "   Environments: Production, Preview, Development"
echo ""
echo "   Variable Name: NODE_ENV"
echo "   Value: production"
echo "   Environments: Production"
echo ""
echo "3. Get MONGODB_URI from backend project:"
echo "   Go to: https://vercel.com/pvagrs-projects/pva-backend-api/settings/environment-variables"
echo "   Find MONGODB_URI value and copy it"
echo ""
echo "   Then add to livestream:"
echo "   Variable Name: MONGODB_URI"
echo "   Value: <paste from backend>"
echo "   Environments: Production, Preview, Development"
echo ""
echo "4. Remove Deployment Protection:"
echo "   Backend:    https://vercel.com/pvagrs-projects/pva-backend-api/settings/deployment-protection"
echo "   Livestream: https://vercel.com/pvagrs-projects/pvabazaar-livestream/settings/deployment-protection"
echo ""
echo "   Set both to 'Only Preview Deployments' or 'None'"
echo ""
echo "5. Redeploy livestream:"
echo "   cd pvabazaar-livestream"
echo "   vercel --prod"
echo ""
echo "6. Test deployments:"
echo "   curl https://pva-backend-h6zkzdmjy-pvagrs-projects.vercel.app/api/health"
echo "   curl -I https://pvabazaar-livestream-o3okjf15o-pvagrs-projects.vercel.app"
echo ""
echo -e "${GREEN}Setup complete! Your production deployment is ready!${NC}"
