export const PUBLIC_ROUTES = [
  {
    key: 'root-home',
    to: '/',
    navLabel: 'Home',
    title: 'Home',
    description: 'Opening homepage and first-step path chooser for visitors.',
    group: 'core',
    badge: 'Entry',
    navPlacement: 'primary',
    access: 'public',
  },
  {
    key: 'get-started',
    to: '/get-started',
    navLabel: 'Get Started',
    title: 'Get Started',
    description: 'Your onboarding entry point for federation features and account setup path.',
    group: 'core',
    badge: 'Start',
    navPlacement: 'primary',
    access: 'public',
  },
  {
    key: 'home',
    to: '/home',
    navLabel: 'Overview',
    title: 'Home',
    description: 'Full landing page and site overview.',
    group: 'core',
    navPlacement: 'primary',
    access: 'public',
  },
  {
    key: 'archive',
    to: '/archive',
    navLabel: 'Library',
    title: 'Library',
    description: 'Browse the living archive and long-form entries.',
    group: 'core',
    badge: 'Foundation',
    navPlacement: 'primary',
    access: 'public',
  },
  {
    key: 'civilization-library',
    to: '/civilization-library',
    navLabel: 'Civilization Library',
    title: 'Civilization Library',
    description: 'Knowledge and worldview-focused reading sections.',
    group: 'support',
    badge: 'Knowledge',
    navPlacement: 'secondary',
    access: 'public',
  },
  {
    key: 'career-quiz',
    to: '/career-quiz',
    navLabel: 'Career Quiz',
    title: 'Career Quiz',
    description: 'Guided assessment and career direction flow.',
    group: 'support',
    navPlacement: 'secondary',
    access: 'public',
  },
  {
    key: 'federation-map',
    to: '/federation-map',
    navLabel: 'Federation Map',
    title: 'Federation Map',
    description: 'Live world pulse map of active passport citizens and contribution roles.',
    group: 'support',
    badge: 'Live',
    navPlacement: 'primary',
    access: 'public',
  },
  {
    key: 'marketplace',
    to: '/marketplace',
    navLabel: 'Marketplace',
    title: 'Marketplace',
    description: 'Artifacts, listings, and commerce surfaces.',
    group: 'core',
    badge: 'Commerce',
    navPlacement: 'primary',
    access: 'public',
  },
  {
    key: 'showroom',
    to: '/showroom',
    navLabel: 'Showroom',
    title: 'Showroom',
    description: 'Curated showcase pages and item presentations.',
    group: 'support',
    badge: 'Display',
    navPlacement: 'secondary',
    access: 'public',
  },
  {
    key: 'governance',
    to: '/proposals',
    navLabel: 'Governance',
    title: 'Governance',
    description: 'The People\'s Proposal Board with endorsement and decision lifecycle.',
    group: 'core',
    badge: 'Civic',
    navPlacement: 'primary',
    access: 'public',
  },
  {
    key: 'conference',
    to: '/conference',
    navLabel: 'Popular Conference',
    title: 'Popular Conference',
    description: 'Popular Conference session workflow and civic execution context.',
    group: 'support',
    badge: 'Civic',
    navPlacement: 'secondary',
    access: 'public',
  },
  {
    key: 'forum',
    to: '/forum',
    navLabel: 'Forum',
    title: 'Forum',
    description: 'Main civic forum with proposal feed and voting.',
    group: 'support',
    badge: 'Featured',
    featured: true,
    navPlacement: 'secondary',
    access: 'public',
  },
  {
    key: 'governance-conference',
    to: '/governance/conference',
    navLabel: 'Governance Conference',
    title: 'Governance Conference',
    description: 'Governance agenda and conference session view.',
    group: 'support',
    navPlacement: 'secondary',
    access: 'citizen',
  },
  {
    key: 'governance-treasury',
    to: '/governance/treasury',
    navLabel: 'Governance Treasury',
    title: 'Governance Treasury',
    description: 'Treasury balances and transparency ledger.',
    group: 'support',
    navPlacement: 'secondary',
    access: 'citizen',
  },
  {
    key: 'download-app',
    to: '/download-app',
    navLabel: 'Download App',
    title: 'Download App',
    description: 'Installable app instructions and quick-access entry.',
    group: 'support',
    navPlacement: 'secondary',
    access: 'public',
  },
  {
    key: 'heelkawn',
    to: '/heelkawn',
    navLabel: 'HeelKawn',
    title: 'HeelKawn',
    description: 'HeelKawn Armory hub with profile, customization, social tools, and mobile/PC downloads.',
    group: 'support',
    navPlacement: 'secondary',
    access: 'public',
  },
  {
    key: 'identity-center',
    to: '/identity-center',
    navLabel: 'Citizen Passport',
    title: 'Citizen Passport',
    description: 'Identity, wallet, governance, and economy records for each citizen node.',
    group: 'support',
    navPlacement: 'secondary',
    access: 'citizen',
  },
  {
    key: 'passport',
    to: '/passport',
    navLabel: 'My Passport',
    title: 'My Passport',
    description: 'Citizen passport profile and wallet identity center.',
    group: 'support',
    navPlacement: 'secondary',
    access: 'citizen',
  },
  {
    key: 'citizens',
    to: '/citizens',
    navLabel: 'Citizens',
    title: 'Citizens',
    description: 'Verified citizen directory and public societal profiles.',
    group: 'support',
    navPlacement: 'secondary',
    access: 'public',
  },
  {
    key: 'creator',
    to: '/creator',
    navLabel: 'Creator Portal',
    title: 'Creator Portal',
    description: 'Creator onboarding and portal entry point.',
    group: 'support',
    navPlacement: 'secondary',
    access: 'public',
  },
  {
    key: 'about',
    to: '/about',
    navLabel: 'About',
    title: 'About',
    description: 'Project and site overview.',
    group: 'support',
    navPlacement: 'primary',
    access: 'public',
  },
]

export const HOME_CORE_ROUTES = PUBLIC_ROUTES.filter((route) => route.group === 'core')
export const HOME_SUPPORT_ROUTES = PUBLIC_ROUTES.filter((route) => route.group === 'support')
