name: Auto Merge Pull Requests

on:
  pull_request:
    types: [labeled]

jobs:
  automerge:
    if: github.event.label.name == 'automerge'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Auto-merge by label
        uses: pascalgn/automerge-action@v0.15.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
